alias ll='ls -lh'
alias la='ls -al'
alias lt='ls -l --time-style=long-iso'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto
#alias grep='grep --color=auto'
#alias fgrep='fgrep --color=auto'
#alias egrep='egrep --color=auto'
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'
